name: Terraform Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: terraform-validation

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main
        with:
          version: '1.4.2'

      - name: Terraform fmt
        run: terraform fmt -check 

      - name: Terraform init
        run: terraform init 

      - name: Terraform validate
        run: terraform validate 